### ISSUE TITLE
webui-popover on checkbox - not showing checkbox as selected

### ISSUE THREAD

**Issue by ssjogus** [sandywalker/webui-popover#159]
hi,

thanks for nice plugin. I am trying to get the popover on checkbox - if a checkbox is clicked it should show, if i uncheck it should hide.

the popover is coming correctly. but problem is, it is not showing checkbox as checked. Any clue how to solve this problem?

here is my code

html:
```
<input type='checkbox' id='check' />click here
<div id='d1' class="webui-popover-content">this is popover div</div>
```

js:
`$('#check').webuiPopover({url:'#d1'});`

and here is screenshot of result:

![popover](https://cloud.githubusercontent.com/assets/8896732/14631908/5ee57c82-0633-11e6-9d22-64a1bfbccbce.png)

**Comment by Edddy** [comment]
Both clicks are interferencing one another. To workaround put popover in manual and trigger it manually. Example:
```

//Initailize
 $('#check').webuiPopover({trigger:'manual'});
...

 //Show it
 $('#check').click() {function() {
      $('#check').webuiPopover('show');
```

**Comment by ssjogus** [comment]
hey,

thanks for your reply.. it is showing me the checkbox checked and popover as well, but it is giving me this error:

`jquery.webui-popover.js:305 Uncaught TypeError: this.options.onShow is not a function`

the code i wrote as you rusggested:
 ```

//Initailize
 $('.check').webuiPopover({trigger:'manual'});

 //Show it
 $('.check').click(function() {
      $('.check').webuiPopover('show');
	  })
```

**Comment by Edddy** [comment]
Complete working sample: https://jsfiddle.net/bu67Lbds/

**Comment by robynjayqueerie** [comment]
I note your example only shows the popup after you have clicked the element. Often you would want the popup to happen as you hover and before you click. I am having the same problem with using it with buttons, the 'hover' method hides my click.on function actually on the button. Is there any way around this besides forcing the popup when you click? Thanks it is a really good piece of work otherwise

**Comment by Edddy** [comment]
I though that was what you want.

If you want to show the popover on hover it's super easy, it's just the default way this plugin works. Here are some samples: https://jsfiddle.net/8nLz1rrx/

**Comment by robynjayqueerie** [comment]
Yes, I acknowledge that your jsFiddle example works but as I mentioned, the popup only comes when you click, if you use the ‘hover’ method it hides the underlying click action, as you say yourself. However, with a button or a checkbox, normally you want the popup to occur before you click, ie when you hover, because you want the user to know what the results of the click will be. But your otherwise very good plugin, prevents the normal click on the button happening, if you use the hover method. It is all about the sequence of when the popup is shown. Sorry if I am not making myself clear.

Regards

 

 

Robyn Hannah PhD BE (Hons 1) Grad Dip Counselling.

 <http://nrie.com.au/NRIEWB9Version/index.html> NRIE Logo

NRI Electronics Pty. Ltd.

PO Box 20, Alstonville, NSW, 2477.

Phone: 02 6628 7961 or 0427 068 257

email:  <mailto:contact@nrie.com.au> mailto:contact@nrie.com.auWeb www.nrie.com.au

**Comment by ssjogus** [comment]
hi @Eddie,

thanks, this was exactly i what wanted. it works really cool..

**Comment by Edddy** [comment]
Excellent @ssjogus! Could you please close the issue so we all help Sandy taking care of the issue list?
