### ISSUE TITLE
is seem that the plugin is no longer supported?

### ISSUE THREAD

**Issue by Se0ng11** [sandywalker/webui-popover#271]

**Comment by Edddy** [comment]
What do you mean by "supported"? It's open source

**Comment by marcosrocha85** [comment]
@Edddy I guess he means "no longer maintained"

**Comment by Edddy** [comment]
@marcosrocha85 Yes, I know what he meant. But the plugin works just fine (I know, because I use it in several production projects), I covers all kind of scenarios, just maybe not your today JS framework of choice, that maybe the author isn't interested in supporting.

**Comment by marcosrocha85** [comment]
@Edddy I just had an issue with popovers inside modal when those have select2 elements. That can be caused because webuipopover creates popovers dinamically and Select2 need to attach an element to work inside modals correctly. I did a workaround by binding the select2 at onShow event of webuipopover.

Anyway, we can always contribute with pull requests. ;)

**Comment by Edddy** [comment]
@marcosrocha85 That's the spirit! I've worked around several issues myself, often related to z-index, etc. Cheers!
