### ISSUE TITLE
Open Popover via jQuery and unbind after certain event

### ISSUE THREAD

**Issue by didadan** [sandywalker/webui-popover#70]
Hi Sandy, thank you for this, great work.

I am building a form validation and if a field is empty I want to show this popover, Maybe I'm a bit off with this implementation. What I go so far is to bind the popover to the right input field. Two things I am missing:

1. Open the popover from jQuery ($('input#emptyfield').click(), $('input#emptyfield').toggle(), and $('input#emptyfield').webuiPopover('show') don't work for me)
2. Unbind the popover from the inputfield so that I can bind it to another one.

This is probably similar to issue " is it possible to initialize pop and show in one click #53 ", however this doesn't work for me.

Do you have any idea how to implement this / is this something your solution can do?
Thank you, Didadan

**Comment by sandywalker** [comment]
Thanks very much for your advice,I didn't consider this situation when wrote the plugin.
The problem is that the plugin auto handled the click event on both trigger element and body, I'm trying to fixed this, my solution is add  trigger option : 'manual' ,  if  trigger is 'manual', the plugin will not handle the    click events. 
Then you can write code like this 
```javascript
        $('#input').webuiPopover();
        $('#input').on('click',function(){
            $(this).webuiPopover('show');
        });
``` 
I'm testing on the solution and will update the code.Hopes it will help you!

**Comment by didadan** [comment]
I guess the same will then possible for 'hide'.

Thanks very much! And also for the quick response.

**Comment by BalakrishnaReddyPolu** [comment]
Hi sandy , thanks for your plugin.

Here i'm trying to add this plugin with react component.
In click event of button , I have written the following code.

      $("#openPopover").webuiPopover({url:'#popoverContent',trigger:'manual',closeable:true});
       $("#openPopover").webuiPopover('show');

popover is opening and content is showing .
but inside content i have React components , there events are not firing due to this i'm unable to change the state of that particular component.

Can you please give me some suggestion , How can I use ?
Thanks.
